language: node_js
node_js:
- 6
install:
- npm install -g hexo
- npm install -g firebase-tools
- npm install
script:
- hexo generate --deploy
after_success:
 -  firebase deploy  -- project riversync-doc -- token $FIREBASE_TOKEN

